# Generated by Django 4.0.6 on 2022-07-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'House Plants'), (2, 'Outdoor Plants'), (3, 'Vegitables')], null=True),
        ),
    ]
