# Generated by Django 4.0.6 on 2022-08-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'House Plants'), (2, 'Outdoor Plants'), (3, 'Vegetables')], null=True),
        ),
    ]
