# Generated by Django 4.1 on 2022-08-04 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_question_starred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
